#spring:
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost/face?characterEncoding=utf-8&useSSL=false
#  jpa:
#    show-sql: true
server:
  context-path: /face
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 1000Mb